//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TypeVisualiser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TypeVisualiser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occured:\n{0}.
        /// </summary>
        internal static string Application_An_Unhandled_Exception_Occurred {
            get {
                return ResourceManager.GetString("Application_An_Unhandled_Exception_Occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Visualiser.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in usage: Attempt to find overlapping areas where the proposed area is NaN..
        /// </summary>
        internal static string Area_OverlapsWith_Error_in_usage_Attempt_to_find_overlapping_areas_where_the_proposed_area_is_NaN {
            get {
                return ResourceManager.GetString("Area_OverlapsWith_Error_in_usage_Attempt_to_find_overlapping_areas_where_the_prop" +
                        "osed_area_is_NaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in usage: given parameter values cannot have less than 2 elements..
        /// </summary>
        internal static string BooleanToAbstractConverter_Convert_Error_in_usage_given_parameter_values_cannot_have_less_than_2_elements {
            get {
                return ResourceManager.GetString("BooleanToAbstractConverter_Convert_Error_in_usage_given_parameter_values_cannot_h" +
                        "ave_less_than_2_elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load your assembly.  There are some dependencies missing from the folder. Make sure all dependencies are in the same folder then retry.
        ///.
        /// </summary>
        internal static string ChooseTypeController_LoadTypes_Unable_to_load_your_assembly {
            get {
                return ResourceManager.GetString("ChooseTypeController_LoadTypes_Unable_to_load_your_assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in usage: angles other than those divisible by 90 are not supported..
        /// </summary>
        internal static string ConnectionRoute_SetHeadTranslate_Error_in_usage_angles_other_than_those_divisible_by_90_are_not_supported {
            get {
                return ResourceManager.GetString("ConnectionRoute_SetHeadTranslate_Error_in_usage_angles_other_than_those_divisible" +
                        "_by_90_are_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in usage: given parameter {0} cannot be null..
        /// </summary>
        internal static string General_Given_Parameter_Cannot_Be_Null {
            get {
                return ResourceManager.GetString("General_Given_Parameter_Cannot_Be_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IL Op Code..
        /// </summary>
        internal static string Globals_LoadOpCodes_Invalid_IL_Op_Code {
            get {
                return ResourceManager.GetString("Globals_LoadOpCodes_Invalid_IL_Op_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad file and/or type in Recently Used File List, cannot load this type, most likely due to missing dependent libraries..
        /// </summary>
        internal static string ModelBuilder_BuildType_Bad_file_and_or_type_in_Recently_Used_File_List_cannot_load_this_type {
            get {
                return ResourceManager.GetString("ModelBuilder_BuildType_Bad_file_and_or_type_in_Recently_Used_File_List_cannot_loa" +
                        "d_this_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type name given doesn&apos;t load from the assembly file name given..
        /// </summary>
        internal static string ModelBuilder_BuildType_The_type_name_given_doesnt_load_from_the_assembly_file_name {
            get {
                return ResourceManager.GetString("ModelBuilder_BuildType_The_type_name_given_doesnt_load_from_the_assembly_file_nam" +
                        "e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResolveEventArgs.RequestingAssembly.Location is null or empty.
        /// </summary>
        internal static string ModelBuilder_OnAssemblyResolve_ResolveEventArgs_RequestingAssembly_Location_is_null_or_empty {
            get {
                return ResourceManager.GetString("ModelBuilder_OnAssemblyResolve_ResolveEventArgs_RequestingAssembly_Location_is_nu" +
                        "ll_or_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recent files list was not in the correct format..
        /// </summary>
        internal static string RecentFilesXml_LoadRecentFiles_The_recent_files_list_was_not_in_the_correct_format {
            get {
                return ResourceManager.GetString("RecentFilesXml_LoadRecentFiles_The_recent_files_list_was_not_in_the_correct_forma" +
                        "t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save recent files xml file.
        ///.
        /// </summary>
        internal static string RecentFilesXml_SaveRecentFile {
            get {
                return ResourceManager.GetString("RecentFilesXml_SaveRecentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the recent files xml.
        ///.
        /// </summary>
        internal static string RecentFilesXml_UnableToLoadRecentFiles {
            get {
                return ResourceManager.GetString("RecentFilesXml_UnableToLoadRecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon in a future version....
        /// </summary>
        internal static string ShellController_ComingSoonExecute_Coming_soon_in_a_future_version {
            get {
                return ResourceManager.GetString("ShellController_ComingSoonExecute_Coming_soon_in_a_future_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to load the diagram file.
        ///.
        /// </summary>
        internal static string ShellController_LoadDiagramFromFile_IO_Error_occurred {
            get {
                return ResourceManager.GetString("ShellController_LoadDiagramFromFile_IO_Error_occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The diagram file is from an old file format version that is no longer supported. The diagram cannot be loaded..
        /// </summary>
        internal static string ShellController_LoadDiagramFromFile_Not_Supported {
            get {
                return ResourceManager.GetString("ShellController_LoadDiagramFromFile_Not_Supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to deserialise the saved diagram. Most likely caused by an unsupported previous version.
        ///.
        /// </summary>
        internal static string ShellController_LoadDiagramFromFile_XML_Deserialisation_error {
            get {
                return ResourceManager.GetString("ShellController_LoadDiagramFromFile_XML_Deserialisation_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to save the diagram.
        ///.
        /// </summary>
        internal static string ShellController_SaveDiagramExecute_IO_Error_Occured {
            get {
                return ResourceManager.GetString("ShellController_SaveDiagramExecute_IO_Error_Occured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to serialise the diagram.
        ///.
        /// </summary>
        internal static string ShellController_SaveDiagramExecute_XML_Serialisation_error {
            get {
                return ResourceManager.GetString("ShellController_SaveDiagramExecute_XML_Serialisation_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no listeners responding to the Get Diagram Size Message..
        /// </summary>
        internal static string ViewportController_CalculateDiagramSize_There_are_no_listeners_responding_to_the_GetDiagramSizeMessage {
            get {
                return ResourceManager.GetString("ViewportController_CalculateDiagramSize_There_are_no_listeners_responding_to_the_" +
                        "GetDiagramSizeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in diagram file.
        /// </summary>
        internal static string ViewportController_Error_in_diagram_file {
            get {
                return ResourceManager.GetString("ViewportController_Error_in_diagram_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected property name given in PropertyChangedMessage.
        /// </summary>
        internal static string ViewportController_OnHide_Unexpected_property_name_given_in_PropertyChangedMessage {
            get {
                return ResourceManager.GetString("ViewportController_OnHide_Unexpected_property_name_given_in_PropertyChangedMessag" +
                        "e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some types in the save file are no longer appear in the assembly:
        ///.
        /// </summary>
        internal static string ViewportController_Some_types_are_not_in_assembly_anymore {
            get {
                return ResourceManager.GetString("ViewportController_Some_types_are_not_in_assembly_anymore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The underlying data object for this subject is not of Visualisable Type Subject Data class..
        /// </summary>
        internal static string VisualisableTypeSubject_GetPersistentData_The_underlying_data_object_for_this_subject_is_not_of_Visualisable_Type_Subject_Data_class {
            get {
                return ResourceManager.GetString("VisualisableTypeSubject_GetPersistentData_The_underlying_data_object_for_this_sub" +
                        "ject_is_not_of_Visualisable_Type_Subject_Data_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This attached property only supports types derived from Control (ie User Control)..
        /// </summary>
        internal static string VisualStateHelper_OnVisualStateNameChanged_This_attached_property_only_supports_types_derived_from_Control {
            get {
                return ResourceManager.GetString("VisualStateHelper_OnVisualStateNameChanged_This_attached_property_only_supports_t" +
                        "ypes_derived_from_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting visual states from within the user control or from binding is not supported. It should be set by the controller.
        /// </summary>
        internal static string VisualStateHelper_SetVisualStateName_Setting_visual_states_from_within_the_user_control {
            get {
                return ResourceManager.GetString("VisualStateHelper_SetVisualStateName_Setting_visual_states_from_within_the_user_c" +
                        "ontrol", resourceCulture);
            }
        }
    }
}
